# Generated by Django 5.1.4 on 2024-12-28 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_proxybaseinfo_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proxybaseinfo',
            options={'ordering': ['name'], 'verbose_name': 'My Custom Model'},
        ),
        migrations.AlterModelTable(
            name='proxybaseinfo',
            table=None,
        ),
    ]
