# Generated by Django 5.1.4 on 2024-12-28 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_proxybaseinfo_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proxybaseinfo',
            options={'ordering': ['name'], 'verbose_name_plural': 'My Custom Model'},
        ),
    ]
