# Generated by Django 5.1.4 on 2024-12-28 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_proxybaseinfo_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='baseinfo',
            table='MainModel',
        ),
    ]
