# Generated by Django 5.1.4 on 2024-12-28 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_baseinfo_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='baseinfo',
            options={'verbose_name': 'My Custom Model'},
        ),
        migrations.AlterModelTable(
            name='baseinfo',
            table=None,
        ),
    ]
