# Generated by Django 5.1.4 on 2024-12-28 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_baseinfo_options_alter_baseinfo_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='baseinfo',
            options={'verbose_name_plural': 'My Custom Model'},
        ),
        migrations.AlterModelOptions(
            name='proxybaseinfo',
            options={'ordering': ['name'], 'verbose_name': 'MyProxyModel'},
        ),
        migrations.AlterModelTable(
            name='proxybaseinfo',
            table=None,
        ),
    ]
