# Generated by Django 5.1.4 on 2024-12-28 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_baseinfo_options_alter_proxybaseinfo_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='baseinfo',
            options={},
        ),
        migrations.AlterModelTable(
            name='baseinfo',
            table='MainModel',
        ),
    ]
