# Generated by Django 5.1.4 on 2024-12-28 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_baseinfo_options_alter_baseinfo_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='baseinfo',
            options={'verbose_name': 'My Custom Model'},
        ),
    ]
