# Generated by Django 5.1.4 on 2024-12-28 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_baseinfo_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='baseinfo',
            options={'verbose_name_plural': 'My Custom Model'},
        ),
    ]
